# Generated by Django 2.2.3 on 2019-07-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='hero_text',
            field=models.CharField(default='text here', help_text='Write an introduction for the bakery',
                                   max_length=255),
        ),
    ]
