# Generated by Django 2.2.3 on 2019-07-28 23:22

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0003_footertext'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading_block', wagtail.core.blocks.StructBlock(
                [('heading_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('size',
                                                                                                     wagtail.core.blocks.ChoiceBlock(
                                                                                                         blank=True,
                                                                                                         choices=[('',
                                                                                                                   'Select a header size'),
                                                                                                                  ('h2',
                                                                                                                   'H2'),
                                                                                                                  ('h3',
                                                                                                                   'H3'),
                                                                                                                  ('h4',
                                                                                                                   'H4')],
                                                                                                         required=False))])),
                                                   ('paragraph_block',
                                                    wagtail.core.blocks.RichTextBlock(icon='fa-paragraph',
                                                                                      template='blocks/paragraph_block.html')),
                                                   ('image_block', wagtail.core.blocks.StructBlock([('image',
                                                                                                     wagtail.images.blocks.ImageChooserBlock(
                                                                                                         required=True)),
                                                                                                    ('caption',
                                                                                                     wagtail.core.blocks.CharBlock(
                                                                                                         required=False)),
                                                                                                    ('attribution',
                                                                                                     wagtail.core.blocks.CharBlock(
                                                                                                         required=False))])),
                                                   ('block_quote', wagtail.core.blocks.StructBlock(
                                                       [('text', wagtail.core.blocks.TextBlock()), ('attribute_name',
                                                                                                    wagtail.core.blocks.CharBlock(
                                                                                                        blank=True,
                                                                                                        label='e.g. Mary Berry',
                                                                                                        required=False))])),
                                                   ('embed_block', wagtail.embeds.blocks.EmbedBlock(
                                                       help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks',
                                                       icon='fa-s15', template='blocks/embed_block.html'))], blank=True,
                                                  verbose_name='Home content block'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_1',
            field=models.ForeignKey(blank=True,
                                    help_text='First featured section for the homepage. Will display up to three child items.',
                                    null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to='wagtailcore.Page', verbose_name='Featured section 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_1_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255,
                                   null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_2',
            field=models.ForeignKey(blank=True,
                                    help_text='Second featured section for the homepage. Will display up to three child items.',
                                    null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to='wagtailcore.Page', verbose_name='Featured section 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_2_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255,
                                   null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_3',
            field=models.ForeignKey(blank=True,
                                    help_text='Third featured section for the homepage. Will display up to six child items.',
                                    null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to='wagtailcore.Page', verbose_name='Featured section 3'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_3_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255,
                                   null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_text',
            field=models.CharField(default='text here', help_text='Write an introduction for the bakery',
                                   max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Homepage image', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_image',
            field=models.ForeignKey(blank=True, help_text='Promo image', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Write some promotional copy', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255,
                                   null=True),
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('introduction', models.TextField(blank=True, help_text='Text to describe the page')),
                ('body', wagtail.core.fields.StreamField([('heading_block', wagtail.core.blocks.StructBlock(
                    [('heading_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('size',
                                                                                                         wagtail.core.blocks.ChoiceBlock(
                                                                                                             blank=True,
                                                                                                             choices=[(
                                                                                                                      '',
                                                                                                                      'Select a header size'),
                                                                                                                      (
                                                                                                                      'h2',
                                                                                                                      'H2'),
                                                                                                                      (
                                                                                                                      'h3',
                                                                                                                      'H3'),
                                                                                                                      (
                                                                                                                      'h4',
                                                                                                                      'H4')],
                                                                                                             required=False))])),
                                                          ('paragraph_block',
                                                           wagtail.core.blocks.RichTextBlock(icon='fa-paragraph',
                                                                                             template='blocks/paragraph_block.html')),
                                                          ('image_block', wagtail.core.blocks.StructBlock([('image',
                                                                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                                                                required=True)),
                                                                                                           ('caption',
                                                                                                            wagtail.core.blocks.CharBlock(
                                                                                                                required=False)),
                                                                                                           (
                                                                                                           'attribution',
                                                                                                           wagtail.core.blocks.CharBlock(
                                                                                                               required=False))])),
                                                          ('block_quote', wagtail.core.blocks.StructBlock(
                                                              [('text', wagtail.core.blocks.TextBlock()), (
                                                              'attribute_name',
                                                              wagtail.core.blocks.CharBlock(blank=True,
                                                                                            label='e.g. Mary Berry',
                                                                                            required=False))])), (
                                                          'embed_block', wagtail.embeds.blocks.EmbedBlock(
                                                              help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks',
                                                              icon='fa-s15', template='blocks/embed_block.html'))],
                                                         blank=True, verbose_name='Page body')),
                ('image', models.ForeignKey(blank=True,
                                            help_text='Landscape mode only; horizontal width between 1000px and 3000px.',
                                            null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                            to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
